### ISSUE TITLE
what would b the diff image 

### ISSUE THREAD

**Issue by saikrishna321** [priyankshah217/ImageCompareFrameworkTestNativeApp#1]
With the below method, what would b the diff image path. I was thinking the diff should b created after asserting two actual and expected.

public static boolean compareImages(String actualImage,
            String expectedImage, String diffImage) throws IOException,
            InterruptedException, IM4JavaException {
        CompareCmd compare = new CompareCmd();
        ArrayListErrorConsumer errorConsumer = new ArrayListErrorConsumer();
        compare.setErrorConsumer(errorConsumer); // for metric-output
        IMOperation cmpOp = new IMOperation();
        cmpOp.addImage();
        cmpOp.addImage();
        cmpOp.metric("RMSE"); // root mean squared (normalized root mean
                                // squared)
        cmpOp.addImage();  
        compare.run(cmpOp, actualImage, expectedImage, diffImage);
        return errorConsumer.getOutput().contains("0 (0)");
    }

**Comment by priyankshah217** [comment]
Diff image would highlight difference between actual and expected images
and stored into separate directory.

**Comment by saikrishna321** [comment]
@priyankshah217  thanks a lot.. what does mask images mean ??

**Comment by saikrishna321** [comment]
@priyankshah217 i'm using the imagesCompare method but for it gives a null error

public class ImageComp {

```
public static void main(String[] args) throws IOException, InterruptedException, IM4JavaException {
    // TODO Auto-generated method stub
     ImageComp comp = new ImageComp();
     comp.compareImages("/Users/saikrisv/Desktop/ActivityScreen1.png",
             "/Users/saikrisv/Desktop/ActivityScreen.png",
             "/Users/saikrisv/Documents/workspace/com.dry.run2/3.png");

    // Runtime.getRuntime().exec("compare 1.png 2.png 3.png");

}

public boolean compareImages(String actualImage,
        String expectedImage, String diffImage) throws IOException,
        InterruptedException, IM4JavaException {
        CompareCmd compare = new CompareCmd();
        ArrayListErrorConsumer errorConsumer = new ArrayListErrorConsumer();
        compare.setErrorConsumer(errorConsumer); // for metric-output
        IMOperation cmpOp = new IMOperation();
        cmpOp.addImage();
        cmpOp.addImage();
        cmpOp.metric("RMSE"); // root mean squared (normalized root mean
        // squared)
        cmpOp.addImage();

        compare.run(cmpOp, actualImage, expectedImage, diffImage);
        return errorConsumer.getOutput().contains("0 (0)");
        }
```

}

Exception in thread "main" org.im4java.core.CommandException: java.lang.NullPointerException
    at org.im4java.core.ImageCommand.run(ImageCommand.java:219)
    at com.test.ImageComp.compareImages(ImageComp.java:36)
    at com.test.ImageComp.main(ImageComp.java:15)
Caused by: java.lang.NullPointerException
    at org.im4java.core.ImageCommand.finished(ImageCommand.java:252)
    at org.im4java.process.ProcessStarter.run(ProcessStarter.java:314)
    at org.im4java.core.ImageCommand.run(ImageCommand.java:215)
    ... 2 more

but when i give noth actual and expected image as the same image it works fine

**Comment by priyankshah217** [comment]
Mask images means, for example.. Ur expected screen has certain portion
which is variable, so these portion will not match with your actual
screenshot in this case you need to mask such portions. So script simply
ignore such portions from actual and expected images.

**Comment by saikrishna321** [comment]
@priyankshah217 can u pls tell why the above code throws a null ?

**Comment by priyankshah217** [comment]
@saikrishna321 , this is bug on imagemagik api.
http://www.imagemagick.org/discourse-server/viewtopic.php?t=24053

They somehow forget to handle NPE. however it generates diff file successfully.

**Comment by saikrishna321** [comment]
@priyankshah217  any help how can i get a workaround ?

**Comment by jitendrapatil542** [comment]
@priyankshah217  do we have workaround for this null point exception error..?
This is my code :

public void compareImagesWithImageMagick (String expected, String actual, String difference) throws Exception {
	CompareCmd compare = new CompareCmd();
        compare.setErrorConsumer(StandardStream.STDERR);
        IMOperation cmpOp = new IMOperation();
        cmpOp.fuzz(5.0);
        cmpOp.metric("AE");
        cmpOp.addImage(expected);
        cmpOp.addImage(actual);
        cmpOp.addImage(difference);
    try {
    	 System.out.println ("Comparison Started!");
        compare.run(cmpOp);
        System.out.println ("Comparison Finished!");       
    }
    catch (Exception ex) {
        throw ex;
    }





Getting this error--------------------------------------------------------------------------------------------------------------------
Comparison Started!
compare: unable to open image 'â€ªD:\ImageMagick\BaseLine\Intro_Page.jpg': Invalid argument @ error/blob.c/OpenBlob/3537.
compare: unable to open image 'â€ªD:\ImageMagick\Actual\IntroPage.jpg': Invalid argument @ error/blob.c/OpenBlob/3537.
compare: unable to open image 'â€ªD:\ImageMagick\Actual\IntroPage.jpg': Invalid argument @ error/blob.c/OpenBlob/3537.
FAILED: test1
org.im4java.core.CommandException: java.lang.NullPointerException
	at org.im4java.core.ImageCommand.run(ImageCommand.java:219)
	at Test.MyTest.compareImagesWithImageMagick(MyTest.java:71)
	at Test.MyTest.test1(MyTest.java:33)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:588)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
	at org.testng.SuiteRunner.run(SuiteRunner.java:286)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
	at org.testng.TestNG.runSuites(TestNG.java:1066)
	at org.testng.TestNG.run(TestNG.java:1034)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.NullPointerException
	at org.im4java.core.ImageCommand.finished(ImageCommand.java:252)
	at org.im4java.process.ProcessStarter.run(ProcessStarter.java:314)
	at org.im4java.core.ImageCommand.run(ImageCommand.java:215)
	... 30 more
